### ISSUE TITLE
https://lts.eclipse.org/ is down

### ISSUE THREAD

**Issue by JonasHelming** [EclipseFdn/lts.eclipse.org#19] opened 2021-06-24 12:20 UTC
Application is not available
The application is currently not serving requests at this endpoint. It may not have been started or is still starting.

Possible reasons you are seeing this page:

The host doesn't exist. Make sure the hostname was typed correctly and that a route matching this hostname exists.
The host exists, but doesn't have a matching path. Check if the URL path was typed correctly and that the route was created using the desired path.
Route and path matches, but all pods are down. Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.

**Comment by autumnfound** [comment] 2021-06-24 12:42
This is directly caused by the OKD cluster outage that is being experienced across many of our sites and products. We will be updating the committer community directly once this is resolved. This issue is external to the site, so once the site is live again we will close this issue!

**Comment by chrisguindon** [comment] 2021-06-24 12:45
Updates are being posted here:
https://www.eclipsestatus.io/

**Closed as completed by chrisguindon** 2021-06-24 12:45 UTC

**Comment by autumnfound** [comment] 2021-06-24 12:49
Site is also back up! Thanks for bringing it to our attention

**Comment by JonasHelming** [comment] 2021-06-24 12:57
Thanks!
